name: Rust

on:
  push:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac:

    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: MacOS
        path: ./target/release/discord-rpc-cli
